services:
  - type: web
    name: course_comparison
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn your_project_name.wsgi:application